version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

pre_build:
  commands:
    - TESTE=$(whereis npm)
    - echo $TESTE
    - npm install

build:
  commands:
    - npm run build

artifacts:
  files:
    - 'dist/*'